# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.IntegerField(choices=[(1, b'student '), (2, b'organization'), (3, b' Committee')], default=1),
        ),
    ]
