# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(choices=[(1, b'student '), (2, b'organization'), (3, b' Committee')], default=1)),
            ],
        ),
    ]
