# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-18 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=b'', max_length=100, unique=True)),
                ('firstname', models.CharField(default=b'', max_length=100)),
                ('lastname', models.CharField(default=b'', max_length=100)),
                ('email', models.EmailField(default=b'example@company.com', max_length=254)),
                ('password', models.CharField(default=b'', max_length=100)),
                ('usertype', models.IntegerField(choices=[(1, b'student '), (2, b'organization'), (3, b' Committee')], default=1)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
