# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-19 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180218_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
